// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/lagzi/EntSymbolBug/ent/runtime.go

const (
	Version = "v0.10.2-0.20220606082056-dd4519f935a6" // Version of ent codegen.
)
