// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PicturesColumns holds the columns for the "pictures" table.
	PicturesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString},
	}
	// PicturesTable holds the schema information for the "pictures" table.
	PicturesTable = &schema.Table{
		Name:       "pictures",
		Columns:    PicturesColumns,
		PrimaryKey: []*schema.Column{PicturesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserPicColumns holds the columns for the "user_pic" table.
	UserPicColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "picture_id", Type: field.TypeInt},
	}
	// UserPicTable holds the schema information for the "user_pic" table.
	UserPicTable = &schema.Table{
		Name:       "user_pic",
		Columns:    UserPicColumns,
		PrimaryKey: []*schema.Column{UserPicColumns[0], UserPicColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_pic_user_id",
				Columns:    []*schema.Column{UserPicColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_pic_picture_id",
				Columns:    []*schema.Column{UserPicColumns[1]},
				RefColumns: []*schema.Column{PicturesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PicturesTable,
		UsersTable,
		UserPicTable,
	}
)

func init() {
	UserPicTable.ForeignKeys[0].RefTable = UsersTable
	UserPicTable.ForeignKeys[1].RefTable = PicturesTable
}
