// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PicturesColumns holds the columns for the "pictures" table.
	PicturesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString},
	}
	// PicturesTable holds the schema information for the "pictures" table.
	PicturesTable = &schema.Table{
		Name:       "pictures",
		Columns:    PicturesColumns,
		PrimaryKey: []*schema.Column{PicturesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserUsertopicedgeColumns holds the columns for the "user_usertopicedge" table.
	UserUsertopicedgeColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "picture_id", Type: field.TypeInt},
	}
	// UserUsertopicedgeTable holds the schema information for the "user_usertopicedge" table.
	UserUsertopicedgeTable = &schema.Table{
		Name:       "user_usertopicedge",
		Columns:    UserUsertopicedgeColumns,
		PrimaryKey: []*schema.Column{UserUsertopicedgeColumns[0], UserUsertopicedgeColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_usertopicedge_user_id",
				Columns:    []*schema.Column{UserUsertopicedgeColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_usertopicedge_picture_id",
				Columns:    []*schema.Column{UserUsertopicedgeColumns[1]},
				RefColumns: []*schema.Column{PicturesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PicturesTable,
		UsersTable,
		UserUsertopicedgeTable,
	}
)

func init() {
	UserUsertopicedgeTable.ForeignKeys[0].RefTable = UsersTable
	UserUsertopicedgeTable.ForeignKeys[1].RefTable = PicturesTable
}
