// Code generated by ent, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgePic holds the string denoting the pic edge name in mutations.
	EdgePic = "pic"
	// Table holds the table name of the user in the database.
	Table = "users"
	// PicTable is the table that holds the pic relation/edge. The primary key declared below.
	PicTable = "user_pic"
	// PicInverseTable is the table name for the Picture entity.
	// It exists in this package in order to avoid circular dependency with the "picture" package.
	PicInverseTable = "pictures"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// PicPrimaryKey and PicColumn2 are the table columns denoting the
	// primary key for the pic relation (M2M).
	PicPrimaryKey = []string{"user_id", "picture_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
