// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeUsertopicedge holds the string denoting the usertopicedge edge name in mutations.
	EdgeUsertopicedge = "usertopicedge"
	// Table holds the table name of the user in the database.
	Table = "users"
	// UsertopicedgeTable is the table that holds the usertopicedge relation/edge. The primary key declared below.
	UsertopicedgeTable = "user_usertopicedge"
	// UsertopicedgeInverseTable is the table name for the Picture entity.
	// It exists in this package in order to avoid circular dependency with the "picture" package.
	UsertopicedgeInverseTable = "pictures"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldAge,
	FieldName,
}

var (
	// UsertopicedgePrimaryKey and UsertopicedgeColumn2 are the table columns denoting the
	// primary key for the usertopicedge relation (M2M).
	UsertopicedgePrimaryKey = []string{"user_id", "picture_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
